module Jekyll
  class HelloTag < Liquid::Tag
    def render(context)
      "This string was generated by actual Ruby code at build time!"
    end
  end
end

Liquid::Template.register_tag('hello_ruby', Jekyll::HelloTag)